services:
  mysql:
    image: mysql:8.0
    container_name: rasmoo-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: senha123
      MYSQL_DATABASE: order_management
      MYSQL_USER: rasmoo
      MYSQL_PASSWORD: r@sm00
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: